### ISSUE TITLE
Funny business with connections when 2 R sessions share the same file queue

### ISSUE THREAD

**Issue by wlandau** [clarkfitzg/phd_research#4]
I'm trying out some code from `filequeue.R`.

```r
rds_queue <- function() file("q.rds", "w+b")

push = function(obj, q = queue) {
  serialize(obj, q, xdr = FALSE)
}

pop = function(q = queue) {
  unserialize(q)
}
```

I opened up 2 parallel interactive R sessions and grabbed the same queue in each.

```r
q <- rds_queue()
```

In Session A, I pushed a message.

```r
q$push(123)
```

I was not able to pop it from Session B.

```r
pop(q)
#> Error in unserialize(q) : error reading from connection
```

**Comment by clarkfitzg** [comment]
Looks like I opened it in the wrong mode. `mode = "w+b"` truncates initially, we need `mode = "r+b"`.

Fixed now, thanks.
